---
abstract: 'Interface to /etc/hosts file'
author:
  - 'Roman M. Parparov <roman@parparov.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Hosts
provides:
  Config::Hosts:
    file: lib/Config/Hosts.pm
    version: 0.01
requires:
  Regexp::IPv6: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
